parameters:
#    igg_user.example.class: Igg\UserBundle\Example

services:
#    igg_user.example:
#        class: %igg_user.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
